version: 0.2

phases:
  install:

    runtime-versions:
      java: corretto11

    pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `javaweb`
      - mvn install
      
  #post_build:
    #commands:
      - mvn package
      - mv target/HELLO-WORLD-1.jar HELLO-WORLD-1.jar
artifacts:
  files:
    - target/HELLO-WORLD-1.jar
    - .ebextensions/**/*