version: 0.2

phases:
  install:

    runtime-versions:
      java: corretto11

    pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `javaweb`
      - mvn install
      
  post_build:
    commands:
      - mvn package
      - mv target/HELLO-WORLD-1.war HELLO-WORLD-1.war
artifacts:
  files:
    - HELLO-WORLD-1.war
    - .ebextensions/**/*